name: Deploy Portfolio

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Execute deployment script
      - name: Run Deployment Script
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: |
          chmod +x ./deploy/build-and-deploy.sh
          ./deploy/build-and-deploy.sh

